### ISSUE TITLE
http_communication_failure

### ISSUE THREAD

**Issue by SiPo79** [se38/twibap#1]
Hi Uwe,

I installed your Twibap Nuggets  - we like to use it in a SAP CRM 7.0 EHP1 Marketing szenario with segmentation.

I think to follow your installation steps correctly - but in any test szenario I get an http_communication_failure at 
client->receive( EXCEPTIONS http_communication_failure = 8 ).

Would be very happy for any help or ideas.

Kind regards,
Simone

**Comment by se38** [comment]
Hi Simone,
difficult to say, this can have a lot of reasons. First of all (please excuse this question): is your system connected to the internet?

**Comment by SiPo79** [comment]
Hey...
...many thanks for answering.
Yes - the system is connected to the Internet - I can look at the requests on the server.
But when I run the coding no request is sending out of the system to the server...

Kind regards,
simone

**Comment by se38** [comment]
Can you please test this little report in your system (this is 7.40 logic, maybe you have to adopt this to a lower release):

```
cl_http_client=>create(
  EXPORTING
    host               = 'www.google.com'
  IMPORTING
    client             = data(client)    " HTTP Client Abstraction
  EXCEPTIONS
    argument_not_found = 1
    plugin_not_active  = 2
    internal_error     = 3
    others             = 4
).

CHECK sy-subrc = 0.

client->send(
  EXCEPTIONS
    http_communication_failure = 1
    http_invalid_state         = 2
    http_processing_failed     = 3
    http_invalid_timeout       = 4
    others                     = 5
).

CHECK sy-subrc = 0.

client->receive(
  EXCEPTIONS
    http_communication_failure = 1
    http_invalid_state         = 2
    http_processing_failed     = 3
    others                     = 4
).

cl_demo_output=>display( client->response->get_cdata( ) ).
```

Three things may happen:
1.) response from Google is returned
2.) response from your Proxy is returned
3.) nothing happens

1.) we have a problem with Twitter/Twibap
2.) read the response: do you need credentials for your Proxy?
3.) the system doesn't have connection to the internet

**Comment by SiPo79** [comment]
I get a connection refused error:

<H2><b>404 Connection refused</b></H2><hr>
Connect to www.google.com:80 failed: NIECONN_REFUSED(‑10)<br><br><br><pre>‑</pre>
<table border="0">

I called our helpdesk - and there is a connection to the internet - but my request doesn't arrive the server...

**Comment by se38** [comment]
Looks like your internet access works thru a proxy server.
Can you please ask your helpdesk for the proxy IP and Port?

In the short report you can change the client creation like this:

```
cl_http_client=>create(
  EXPORTING
    host               = 'www.google.com'
    proxy_host  =  '111.222.111.111'    "the IP address of your proxy server
    proxy_service = '4711'            "the port of your proxy server
  IMPORTING
    client             = data(client)    " HTTP Client Abstraction
  EXCEPTIONS
    argument_not_found = 1
    plugin_not_active  = 2
    internal_error     = 3
    others             = 4
).
```

**Comment by SiPo79** [comment]
YEAH - it works! 
Many, many thanks.... I get response from google :)
Now I have to transfer the proxy connection details to the ZCL_OAUTH class...

Kind regards,
simone

**Comment by SiPo79** [comment]
Changed ZCL_OAUTH:

 cl_http_client=>create(
    EXPORTING
      host   = api_host
      scheme = api_protocol
      proxy_host  =  'proxy.XXX.net'  
      proxy_service = '8080'
    IMPORTING
      client = client
    EXCEPTIONS
      argument_not_found = 1
      plugin_not_active  = 2
      internal_error     = 3
      ).

and run:
  twitter_api = zcl_twa_api=>getapi(
                          screen_name = 'ABC'
                          password    = '123'
                          ).
    statuses = twitter_api->timeline_res->home_timeline( ).

and get HTTP_COMMUNICATION_FAILURE

**Comment by se38** [comment]
The user registration worked for you? (Report Z_OAUTH_SETUP_2_REGISTER_USER).
Have you followed the installation process regarding the SSL certificate? (see https://github.com/se38/ZOAuth#installation )

**Comment by SiPo79** [comment]
Hey uwe...

...sorry for the delay.
The problem is actually raised by the https access...

I am on the right track now....thanks a lot for your help und support...

Kind regards and many thanks,
Simone

**Comment by se38** [comment]
No problem. Please report back if you get it to run (and in case you still have problems of course).

**Comment by SiPo79** [comment]
![system](https://cloud.githubusercontent.com/assets/11437573/6709169/10d1fe6c-cd77-11e4-9c47-f2f45781a844.JPG)

..still have problems - I believe it is on the certificate..?!?

**Comment by se38** [comment]
To be honest: So sorry, but I have no idea (I'm not a basis guy). At home back then I've tried until it worked. The important message IMHO is "SSL Peer Certificate Untrusted".
I think you should open a question on SCN (Space "SAP NetWeaver Administrator" http://scn.sap.com/community/netweaver-administrator ). If you do so, please post a link to your question here in case other users of Twibap have the same problems.

**Comment by rajanarayanan** [comment]
Hi Uwe,

I am getting the error when executing the report Z_OAUTH_SETUP_2_REGISTER_USER, 
Error: HTTP_COMMUNICATION_FAILURE.

After seeing the previous discussion, I followed these steps, but still its not working for me.

1) uploaded the streamwork certificate using this reference
http://wiki.scn.sap.com/wiki/display/SWAPI/Importing+StreamWork+SSL+certificate+into+ABAP+systems

2)After  updating the certificate and re-run the report i get the error again .so i searched in google and found this link and tried, but still i am getting the error
http://scn.sap.com/thread/3681968

Error i am getting like this in the SMICM trace 
"**\* ERROR => IcmConnInitClientSSL: SapSSLSessionStart failed (-102): SSSLERR_PEER_CERT_UNTRUSTED {00074346} [icxxconn_mt.c"

3) I had a doubt whether my system is connected to internet or not, so i tried pinging google code which is giving by you.. and it is working good for me.. and the system is connect to internet.

now I am struck and i don't know what i did wrong.

So it will be really appreciated if you could help me and let me know is there any way we can get rid of this issue and register the user.

Thanks & Regards,
Raja

**Comment by se38** [comment]
Hi Raja,

the streamwork certificate was just an excample on how to import certificates. If you want to use Twitter you have to import the certificate from twitter.com

Please report back (positive and negative)

**Comment by rajanarayanan** [comment]
Thank you for your quick response.

I have imported Twitter Certificated. But still am facing the same error.
More details towards the Trace.....

**\* ERROR during SecudeSSL_SessionStart() from SSL_connect()==SSL_ERROR_SSL
   session uses PSE file "/usr/sap/D01/DVEBMGS00/sec/SAPSSLC.pse"
SecudeSSL_SessionStart: SSL_connect() failed
  secude_error 536872221 (0x2000051d) = "SSL API error"

> > ```
> >        Begin of Secude-SSL Errorstack            >>
> > ```
> > 
> > 0x2000051d   SAPCRYPTOLIB   SSL_connect
> > SSL API error
> > Failed to verify peer certificate. Peer not trusted.
> > 0xa0600203   SSL   ssl_verify_peer_certificates
> > Peer not trusted
> > 0xa0600297   SSL   ssl_cert_checker_verify_certificates
> > peer certificate (chain) is not trusted
> > Certificate:
> >   Certificate:
> >       Subject     :CN=api.twitter.com, OU=Twitter Security, O="Twitter, Inc.", L=San Francisco, SP=California, C=US
> >       Issuer      :CN=VeriSign Class 3 Secure Server CA - G3, OU=Terms of use at https://www.verisign.com/rpa (c)10, OU=Ver
> >       Serial number:0x7047180ea2df95016caea3c95aec4345
> >       Validity:
> >         Not before  :Sat Aug  2 19:00:00 2014
> >         Not after   :Sat Dec 31 18:59:59 2016

**Comment by se38** [comment]
Hi Raja,
In this case I only can repeat myself: for the "SSL Peer Certificate Untrusted" error you should open a question on SCN (Space "SAP NetWeaver Administrator" http://scn.sap.com/community/netweaver-administrator ).
